package leadmyteam;

import java.sql.Date;
import javax.swing.JOptionPane;

public class DodajProjekt extends javax.swing.JFrame {

    private LeadMyTeam leadMyTeam;
    private String nazwaProjektu;
    private Date dataRozp;
    private Date dataZak;
    
    private String uczestnik;
    private String[] tokens = null;
    
    public DodajProjekt(LeadMyTeam lmt) {
        this.leadMyTeam = lmt;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        //setAlwaysOnTop(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NazwaProjektuTextField = new javax.swing.JTextField();
        StartDateChooser = new com.toedter.calendar.JDateChooser();
        KoniecDateChooser = new com.toedter.calendar.JDateChooser();
        UczestnicyTextField = new javax.swing.JTextField();
        AddProjectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dodaj projekt");

        jLabel2.setText("Nazwa projektu");

        jLabel3.setText("Data rozpoczęcia");

        jLabel4.setText("Data Zakończenia");

        jLabel5.setText("Uczestnicy");

        StartDateChooser.setDateFormatString("dd-MM-yyyy");

        KoniecDateChooser.setDateFormatString("dd-MM-yyyy");

        AddProjectButton.setText("Dodaj");
        AddProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProjectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NazwaProjektuTextField)
                    .addComponent(StartDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(KoniecDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UczestnicyTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddProjectButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NazwaProjektuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(StartDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(KoniecDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(UczestnicyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddProjectButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProjectButtonActionPerformed
        this.nazwaProjektu = NazwaProjektuTextField.getText();
        java.util.Date dataRoz = StartDateChooser.getDate();
        this.dataRozp = new Date(dataRoz.getTime());
        java.util.Date dataZakon = KoniecDateChooser.getDate();
        this.dataZak = new Date(dataZakon.getTime());
        this.uczestnik = UczestnicyTextField.getText();
        
        if (dataZak.getTime()-dataRoz.getTime()<0){
            StartDateChooser.setDate(null);
            KoniecDateChooser.setDate(null);
            JOptionPane.showMessageDialog(null, "Nie możemy cofać się w czasie");
            return;
        }
            
        tokens = uczestnik.split(",");
        
        if (leadMyTeam.sqlConn.znajdzProjektPoNazwie(nazwaProjektu) != null) {
            JOptionPane.showMessageDialog(this, "Projekt " + nazwaProjektu + " już istnieje.");
            return;
        } else {
            for(String x : tokens){
                if(leadMyTeam.sqlConn.znajdzPracownika(x) != null){

                    leadMyTeam.sqlConn.DodajProjekt(nazwaProjektu, dataRozp, dataZak);
                    leadMyTeam.sqlConn.DodajUczestnika(nazwaProjektu, tokens);

                    leadMyTeam.OdswiezProjekty();
                    this.dispose();

                    JOptionPane.showMessageDialog(null, "Dodano projekt " + nazwaProjektu);
                } else {
                    JOptionPane.showMessageDialog(null, "Pracownik " + x + " nie istnieje");
                }
            }
        }
    }//GEN-LAST:event_AddProjectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DodajProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DodajProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DodajProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DodajProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProjectButton;
    private com.toedter.calendar.JDateChooser KoniecDateChooser;
    private javax.swing.JTextField NazwaProjektuTextField;
    private com.toedter.calendar.JDateChooser StartDateChooser;
    private javax.swing.JTextField UczestnicyTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
