package leadmyteam;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.plaf.basic.BasicTabbedPaneUI;
import javax.swing.table.TableModel;

public class LeadMyTeam extends javax.swing.JFrame {

    JTable tabelaPracownikow;
    String selectedContentPracownicy = null;
    String selectedContentUrlopy = null;
    String selectedContentProjekty = null;
    String[] PracownicyColumnsNames = {
        "Pesel",
        "Imie",
        "Nazwisko",
        "Adres",
        "Miasto",
        "Kod Pocztowy",
        "Kraj",
        "Stanowisko",
        "Liczba Godzin",
        "Wyplata"};

    String[] UrlopyColumnsNames = {
        "Pesel",
        "Imie",
        "Nazwisko",
        "Data Rozpoczecia",
        "Data Zakonczenia"};
    
    String[] ProjektyColumnsNames = {
        "ID Projektu",
        "Nazwa Projektu",
        "Data Oddania",
        "Data Rozpoczecia"
    };

    public SqlConnection sqlConn;

    public LeadMyTeam() {
        sqlConn = new SqlConnection();
        sqlConn.PobierzPracownikowZBazyDanych();
        sqlConn.PobierzUrlopyZBazyDanych();
        sqlConn.PobierzProjektyZBazyDanych();
        initComponents();
        setLocationRelativeTo(null);
        //setExtendedState(MAXIMIZED_BOTH);
        jTable1.setRowHeight(40);
        jTable2.setRowHeight(40);
        jTable3.setRowHeight(40);
        OdswiezPracownikow();
        OdsiwezUrlopy();
        OdswiezProjekty();
        jTabbedPane1.setUI(new BasicTabbedPaneUI());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserSave = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        AddButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        ComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        AddButton2 = new javax.swing.JButton();
        DeleteButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        DisplayButton3 = new javax.swing.JButton();
        AddButton3 = new javax.swing.JButton();
        DeleteButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        SzczegolyButton = new javax.swing.JButton();
        javax.swing.JMenuBar jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jFileChooserSave.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LeadMyTeam");

        AddButton.setText("Dodaj pracownika");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Usuń pracownika");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Nazwisko", "PESEL" }));
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText(" Sortowanie:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(AddButton)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteButton)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista pracowników", jPanel1);

        AddButton2.setText("Dodaj urlop");
        AddButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButton2ActionPerformed(evt);
            }
        });

        DeleteButton2.setText("Usuń urlop");
        DeleteButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText(" Sortowanie:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Nazwisko", "PESEL" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable2FocusLost(evt);
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AddButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addComponent(DeleteButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(AddButton2)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteButton2)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Urlopy", jPanel2);

        DisplayButton3.setText("Odśwież");
        DisplayButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayButton3ActionPerformed(evt);
            }
        });

        AddButton3.setText("Dodaj projekt");
        AddButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButton3ActionPerformed(evt);
            }
        });

        DeleteButton3.setText("Usuń projekt");
        DeleteButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText(" Sortowanie:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Nazwa", "ID" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        SzczegolyButton.setText("Szczegóły");
        SzczegolyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SzczegolyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(DisplayButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, 141, Short.MAX_VALUE)
                    .addComponent(SzczegolyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(DisplayButton3)
                        .addGap(18, 18, 18)
                        .addComponent(AddButton3)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteButton3)
                        .addGap(18, 18, 18)
                        .addComponent(SzczegolyButton)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Projekty", jPanel3);

        jMenu1.setText("Plik");

        jMenuItem3.setText("Wyeksportuj pracownikow");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Wyeksportuj urlopy");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Wyeksportuj projekty");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar.add(jMenu1);

        jMenu3.setText("Pomoc");

        jMenuItem4.setText("O Programie");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem1.setText("Autorzy");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar.add(jMenu3);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        switch (ComboBox.getSelectedItem().toString()) {
            case "Nazwisko":
                sqlConn.Sort1();
                OdswiezPracownikow();
                break;

            case "PESEL":
                sqlConn.SortPesel();
                OdswiezPracownikow();
                break;
        }
    }//GEN-LAST:event_ComboBoxActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        if (selectedContentPracownicy != null) {
            UsunPracownika up = new UsunPracownika(this, selectedContentPracownicy,
                    sqlConn.znajdzPracownika(selectedContentPracownicy).PobierzImie(),
                    sqlConn.znajdzPracownika(selectedContentPracownicy).PobierzNazwisko());
            up.setVisible(true);
            selectedContentPracownicy = null;
        } else {
            JOptionPane.showMessageDialog(this, "Nie zaznaczono żadnego pracownika");
        }
        OdswiezPracownikow();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        DodajPracownika dp = new DodajPracownika(this);
        dp.setVisible(true);
        OdswiezPracownikow();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void AddButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButton2ActionPerformed
        if (selectedContentPracownicy != null) {
            DodajUrlop du = new DodajUrlop(this, selectedContentPracownicy);
            du.setVisible(true);
        } else {
            DodajUrlop du = new DodajUrlop(this);
            du.setVisible(true);
        }
        OdsiwezUrlopy();
    }//GEN-LAST:event_AddButton2ActionPerformed

    private void DeleteButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButton2ActionPerformed
        if (selectedContentUrlopy != null) {
            UsunUrlop uu = new UsunUrlop(this, selectedContentUrlopy,
            sqlConn.znajdzUrlop(selectedContentUrlopy).PobierzImie(),
            sqlConn.znajdzUrlop(selectedContentUrlopy).PobierzNazwisko());
            selectedContentUrlopy = null;
            uu.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Nie zaznaczono żadnego urlopu");
        }
        OdsiwezUrlopy();
    }//GEN-LAST:event_DeleteButton2ActionPerformed

    private void AddButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButton3ActionPerformed
        DodajProjekt dp = new DodajProjekt(this);
        dp.setVisible(true);
        OdswiezProjekty();
    }//GEN-LAST:event_AddButton3ActionPerformed

    private void DeleteButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButton3ActionPerformed
        UsunProjekt up = new UsunProjekt(this);
        up.setVisible(true);
        OdswiezProjekty();
    }//GEN-LAST:event_DeleteButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        selectedContentPracownicy = jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0).toString();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        selectedContentUrlopy = jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 0).toString();
    }//GEN-LAST:event_jTable2MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        switch (jComboBox2.getSelectedItem().toString()) {
            case "Nazwisko":
                sqlConn.sortujUrlopyPoNazwisku();
                OdsiwezUrlopy();
                break;

            case "PESEL":
                sqlConn.sortujUrlopyPoPeselu();
                OdsiwezUrlopy();
                break;
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost

    }//GEN-LAST:event_jTable1FocusLost

    private void jTable2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable2FocusLost

    }//GEN-LAST:event_jTable2FocusLost

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        selectedContentProjekty = jTable3.getModel().getValueAt(jTable3.getSelectedRow(), 0).toString();
    }//GEN-LAST:event_jTable3MouseClicked

    private void SzczegolyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SzczegolyButtonActionPerformed
        Szczegoly s = new Szczegoly(this);
        s.setVisible(true);
        // TODO add your handling code here:
        // Do zrobienia szczególy projektów
        // Tak jak w poprzednich przypadkach stworzyłem listę projekty która składa się z klas Projekt
        // Projekt ma w sobie, ID, Nazwe, DateRozpoczecia, DateOddania oraz Liste (klasy) Procownik w której znajdują się pracownicy
        // uczestniczący w danym projekcie, czyli w szczególach trzeba po prostu w jakieś tabeli wyświetlic tych pracowników
        // z danego projektu.
    }//GEN-LAST:event_SzczegolyButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Autorzy a = new Autorzy();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void DisplayButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayButton3ActionPerformed
        sqlConn.PobierzProjekty();
        OdswiezProjekty();
    }//GEN-LAST:event_DisplayButton3ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        switch (jComboBox3.getSelectedItem().toString()) {
            case "Nazwa":
                sqlConn.sortujProjektyPoNazwie();
                OdswiezProjekty();
                break;

            case "ID":
                sqlConn.sortujProjektyPoId();
                OdswiezProjekty();
                break;
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        About a = new About();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jFileChooserSave.setSelectedFile(new File("pracownicy.xls"));
        jFileChooserSave.setFileFilter(new FileNameExtensionFilter("xml file","xml"));
        int odpowiedz = jFileChooserSave.showSaveDialog(this);
            if (odpowiedz == jFileChooserSave.APPROVE_OPTION) {
                File file = jFileChooserSave.getSelectedFile();
                try {
                    TableModel model = jTable1.getModel();
                    
                    FileWriter output = new FileWriter(file);
                    
                    for(int i = 0; i <model.getColumnCount(); i++){
                        output.write(model.getColumnName(i) + "\t");
                    }
                    output.write("\n");
                    for(int k=0;k<model.getRowCount();k++) {
                        for(int j=0;j<model.getColumnCount();j++) {
                            output.write(model.getValueAt(k,j).toString()+"\t");
                        }
                        output.write("\n");
                    }
                    output.close();
                } catch(Exception e) {
                    e.printStackTrace();
                }
            }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jFileChooserSave.setSelectedFile(new File("urlopy.xls"));
        jFileChooserSave.setFileFilter(new FileNameExtensionFilter("xml file","xml"));
        int odpowiedz = jFileChooserSave.showSaveDialog(this);
            if (odpowiedz == jFileChooserSave.APPROVE_OPTION) {
                File file = jFileChooserSave.getSelectedFile();
                try {
                    TableModel model = jTable2.getModel();
                    
                    FileWriter output = new FileWriter(file);
                    
                    for(int i = 0; i <model.getColumnCount(); i++){
                        output.write(model.getColumnName(i) + "\t");
                    }
                    output.write("\n");
                    for(int k=0;k<model.getRowCount();k++) {
                        for(int j=0;j<model.getColumnCount();j++) {
                            output.write(model.getValueAt(k,j).toString()+"\t");
                        }
                        output.write("\n");
                    }
                    output.close();
                } catch(Exception e) {
                    e.printStackTrace();
                }
            }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jFileChooserSave.setSelectedFile(new File("projekty.xls"));
        jFileChooserSave.setFileFilter(new FileNameExtensionFilter("xml file","xml"));
        int odpowiedz = jFileChooserSave.showSaveDialog(this);
            if (odpowiedz == jFileChooserSave.APPROVE_OPTION) {
                File file = jFileChooserSave.getSelectedFile();
                try {
                    TableModel model = jTable3.getModel();
                    
                    FileWriter output = new FileWriter(file);
                    
                    for(int i = 0; i <model.getColumnCount(); i++){
                        output.write(model.getColumnName(i) + "\t");
                    }
                    output.write("\n");
                    for(int k=0;k<model.getRowCount();k++) {
                        for(int j=0;j<model.getColumnCount();j++) {
                            output.write(model.getValueAt(k,j).toString()+"\t");
                        }
                        output.write("\n");
                    }
                    output.close();
                } catch(Exception e) {
                    e.printStackTrace();
                }
            }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    public void OdswiezPracownikow() {
        String pracownicy = "";
        for (int i = 0; i < sqlConn.Pracownicy.size(); i++) {
            pracownicy += sqlConn.Pracownicy.get(i).PobierzDane() + "\n";
        }

        jTable1.setModel(new DefaultTableModel(sqlConn.PobierzPracownikow(), PracownicyColumnsNames));
        jTable1.getModel().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                float wyplata = Float.parseFloat(jTable1.getModel().getValueAt(e.getLastRow(), 9).toString());
                int liczbaGodzin = Integer.parseInt(jTable1.getModel().getValueAt(e.getLastRow(), 8).toString());
                float stawkaGodzinowa = wyplata / (float) liczbaGodzin;
                sqlConn.ZmienDanePracownika(
                        e.getColumn(),
                        jTable1.getModel().getValueAt(e.getLastRow(), 0).toString(), //pesel
                        jTable1.getModel().getValueAt(e.getLastRow(), 1).toString(), //imie,
                        jTable1.getModel().getValueAt(e.getLastRow(), 2).toString(), //nazwisko,
                        jTable1.getModel().getValueAt(e.getLastRow(), 3).toString(), //adres,
                        jTable1.getModel().getValueAt(e.getLastRow(), 4).toString(), //miasto,
                        jTable1.getModel().getValueAt(e.getLastRow(), 5).toString(), //kodpocztowy,
                        jTable1.getModel().getValueAt(e.getLastRow(), 6).toString(), //kraj,
                        jTable1.getModel().getValueAt(e.getLastRow(), 7).toString(), //nazwaStanowiska,
                        liczbaGodzin, //liczbaGodzin,
                        stawkaGodzinowa //stawkaGodzinowa);
                );
                OdswiezPracownikow();
            }
        });
    }

    public void OdsiwezUrlopy() {
        jTable2.setModel(new DefaultTableModel(sqlConn.PobierzUrlopy(), UrlopyColumnsNames));
    }
    
    public void OdswiezProjekty(){
        jTable3.setModel(new DefaultTableModel(sqlConn.PobierzProjekty(), ProjektyColumnsNames));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeadMyTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeadMyTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeadMyTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeadMyTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeadMyTeam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton AddButton2;
    private javax.swing.JButton AddButton3;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton DeleteButton2;
    private javax.swing.JButton DeleteButton3;
    private javax.swing.JButton DisplayButton3;
    private javax.swing.JButton SzczegolyButton;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JFileChooser jFileChooserSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
